6113_DanilyUK_ZheleznOV
itsecd/academic-lab-1 pull request #6
Opened 2024-02-23 15:36 UTC by SnowDrop163

2024-02-29 05:26 UTC, vicanfed requested changes
Неплохо, но многое нужно переделать.

[6113_DanilyUK_ZheleznOV.docx](https://github.com/itsecd/academic-lab-1/files/14443240/6113_DanilyUK_ZheleznOV.docx)

2024-03-02 02:25 UTC, SnowDrop163 commented
[6113_DanilyUK_ZheleznOV (1).docx](https://github.com/itsecd/academic-lab-1/files/14467767/6113_DanilyUK_ZheleznOV.1.docx)

2024-03-07 04:56 UTC, SnowDrop163 commented
[6113_DanilyUK_ZheleznOV.docx](https://github.com/itsecd/academic-lab-1/files/14518921/6113_DanilyUK_ZheleznOV.docx)
Переделанная 1 лаба

2024-03-07 05:06 UTC, SnowDrop163 commented
[6113_DanilyUK_ZheleznOV.docx](https://github.com/itsecd/academic-lab-1/files/14518993/6113_DanilyUK_ZheleznOV.docx)
Переделанная 1 лаба

2024-03-07 05:28 UTC, vicanfed commented
Гораздо лучше, но чуть-чуть ещё надо подправить.
Отправлять больше PR не требуется. После исправлений работу примет преподаватель в классе.
[6113_DanilyUK_ZheleznOV.1.docx](https://github.com/itsecd/academic-lab-1/files/14519131/6113_DanilyUK_ZheleznOV.1.docx)

2024-03-08 18:27 UTC, closed without merging