6114_Sheff_Strebelev
itsecd/academic-lab-1 pull request #9
Opened 2024-03-06 14:38 UTC by sh1kaff

2024-03-06 14:40 UTC, sh1kaff commented
если легче
https://docs.google.com/document/d/1XxB-qczXjiCTNkTGuyNfUOM4rA9erIYhPc9XbeZ-69Y/edit

2024-03-07 08:38 UTC, vicanfed requested changes
Требуется существенная переработка
[6114_Strebelev_Sheff.docx](https://github.com/itsecd/academic-lab-1/files/14521242/6114_Strebelev_Sheff.docx)

2024-03-13 09:55 UTC, sh1kaff commented
а над чем нам конкретно нужно подумать при переработке идеи и недостатка?

2024-03-13 10:03 UTC, vicanfed commented
В файле достаточно конкретно изложены замечания.
Также рекомендую перечитать https://docs.google.com/document/d/17pliktRpPX6av2e_oDm_T6i2Sy4YZdFhQUj2WMuOjEs/edit?usp=sharing
и https://github.com/itsecd/academic-fundamentals/blob/main/lab-1/lab-1-task.pdf

2024-03-14 07:21 UTC, closed without merging